### ISSUE TITLE
HomeAssistantPackage nearly all deprecated and not working

### ISSUE THREAD

**Issue by bwims** [gpbenton/engMQTTClient#34]
Hi,

I guess you aren't using HA with this anymore, but I thought I'd better let you know that all MQTT sensors now have to be under mqtt: in yaml, so the HA Package isn't much use now.

It's driving me mad trying to rework everything.  Ah well.

**Comment by gpbenton** [comment]
Actually I spent (wasted) a morning updating my yaml files over the holidays doing my annual HA update.

I had completely forgotten about the example here, I'll rewrite it in the new style when I get a chance.

Thanks for reminding me.

**Comment by bwims** [comment]
Oh Wow!  

You truly are a hero!  

Thank you, thank you!

Signed,  HA novice, totally out of his depth!

**Comment by gpbenton** [comment]
I have copied a trv package using the new format to the wiki page.

Hope it helps.

**Comment by bwims** [comment]
Many thanks for that!   

Did you decide to not bother with the Statistics platform in the end?

I had to go archive.org in the end to find the original functionality which was a whole bunch of stats, each of which now required it's own statistics block!  What a disappointment!


I worked out that for the mean, you would need this, after the switch: declaration

```
  sensor:
    - platform: statistics
      name: bedroom_etrv_stats
      entity_id: sensor.bedroom_temperature
      state_characteristic: mean
      max_age:
        minutes: 25
```

Out of interest, what did you use it for?  I'm guessing it was to smooth out the sensor values over time?

Thanks again!

B.
